name: Deploy to dev environment

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy microfrontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Replace urls
        run: sed -i 's/https:\/\/basisvisualisierung.niedersachsen.de/https:\/\/dev.basisvisualisierung.niedersachsen.de/g' ./app.js
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
      - name: Install and build
        run: |
          npm install
          npm run build
      - name: Download minio
        run: |
          curl https://dl.minio.io/client/mc/release/linux-amd64/mc --output ./mc
          chmod u+x ./mc
      - name: Setup alias
        run: ./mc alias set upload https://s3.eu-de.cloud-object-storage.appdomain.cloud ${{ secrets.IBM_COS_DEV_ACCESS_KEY }} ${{ secrets.IBM_COS_DEV_SECRET_KEY }}
      - name: Upload file
        run: ./mc cp ./dist/vt-microfrontend.min.js upload${{ secrets.IBM_COS_PATH_DEV }}